# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvatch < Formula
  desc "Kvatch CLI"
  homepage "https://github.com/kvatch-hub/kvatch-cli"
  version "0.5.0-alpha.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.4/kvatch-cli_0.5.0-alpha.4_darwin_amd64.tar.gz"
      sha256 "e6ec07ce71057b88ae58e4f6b47c013637fb07bb2fe04dd92f6e642a05f56da2"

      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.4/kvatch-cli_0.5.0-alpha.4_darwin_arm64.tar.gz"
      sha256 "d43ba401ddf63782c4556ec46395ab99f615e212939b1816865db0daec639d59"

      def install
        bin.install "kvatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.4/kvatch-cli_0.5.0-alpha.4_linux_amd64.tar.gz"
      sha256 "7b3e277e0d09365ef1c64adfc369d5fbd986e8b75990b6ba6fa18139a9167e98"
      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.4/kvatch-cli_0.5.0-alpha.4_linux_arm64.tar.gz"
      sha256 "e8ed4ed5c62704b4a79735e4d2431556771d27042a392e0c4f5acb5986d13730"
      def install
        bin.install "kvatch"
      end
    end
  end

  test do
    system "#{bin}/kvatch", "--version"
  end
end
