# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvatch < Formula
  desc "Kvatch CLI"
  homepage "https://github.com/kvatch-hub/kvatch-cli"
  version "0.5.0-alpha.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.5/kvatch-cli_0.5.0-alpha.5_darwin_amd64.tar.gz"
      sha256 "211a0166c0004ffb523423dce82da6d26412fd2e00aaa5f442284bbccef2f7b0"

      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.5/kvatch-cli_0.5.0-alpha.5_darwin_arm64.tar.gz"
      sha256 "af0ebfe0bb221970cc1724a17d7e05b83bea94a9474b036ba449e3aaea3de604"

      def install
        bin.install "kvatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.5/kvatch-cli_0.5.0-alpha.5_linux_amd64.tar.gz"
      sha256 "9a87af4a2f4417e53972f458b1f2bd322c60e72fd1e88b09efff08fdbc10e8ba"
      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.5/kvatch-cli_0.5.0-alpha.5_linux_arm64.tar.gz"
      sha256 "9bbedd92b33f63a1a945002afcb013417a61d5f10f38ded582955b5258af9739"
      def install
        bin.install "kvatch"
      end
    end
  end

  test do
    system "#{bin}/kvatch", "--version"
  end
end
