# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvatch < Formula
  desc "Kvatch CLI"
  homepage "https://github.com/kvatch-hub/kvatch-cli"
  version "0.5.0-beta.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-beta.4/kvatch-cli_0.5.0-beta.4_darwin_amd64.tar.gz"
      sha256 "32a6e0740f042a21f8c6a02aebeb1a6aa149b63f306abc3705c16c62da5cab12"

      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-beta.4/kvatch-cli_0.5.0-beta.4_darwin_arm64.tar.gz"
      sha256 "66a3c137297066570de18b5b85317d87fee13cf5f0fb82187792a4861975097a"

      def install
        bin.install "kvatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-beta.4/kvatch-cli_0.5.0-beta.4_linux_amd64.tar.gz"
      sha256 "3c2359d2e4eb160fe5dedcbc400d23e828e6468bd614a375ad8e3b8d749a7e08"
      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-beta.4/kvatch-cli_0.5.0-beta.4_linux_arm64.tar.gz"
      sha256 "cd0ed81c9df95c712b362f1d54bfd87f81e3fcfe8d3e3f8ffc9dae6f85018778"
      def install
        bin.install "kvatch"
      end
    end
  end

  test do
    system "#{bin}/kvatch", "--version"
  end
end
