# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvatch < Formula
  desc "Kvatch CLI"
  homepage "https://github.com/kvatch-hub/kvatch-cli"
  version "0.5.0-alpha.16"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.16/kvatch-cli_0.5.0-alpha.16_darwin_amd64.tar.gz"
      sha256 "6be4291413132af8e220ee2af257c159354a65af03f69a22d432897728aa8f8f"

      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.16/kvatch-cli_0.5.0-alpha.16_darwin_arm64.tar.gz"
      sha256 "1cca506ca26e7da9a586ee318e20006a95f5d0fec33ca2e03787e836f53716af"

      def install
        bin.install "kvatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.16/kvatch-cli_0.5.0-alpha.16_linux_amd64.tar.gz"
      sha256 "ee23c6c436693b5f90cd75262c695f2be3986a89f5eb8be5984312b483db2c38"
      def install
        bin.install "kvatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kvatch-hub/kvatch-cli/releases/download/v0.5.0-alpha.16/kvatch-cli_0.5.0-alpha.16_linux_arm64.tar.gz"
      sha256 "60d256708048b64c8584dc5e041234252fc98fec869fa923211d4fb2e512c38c"
      def install
        bin.install "kvatch"
      end
    end
  end

  test do
    system "#{bin}/kvatch", "--version"
  end
end
